### ISSUE TITLE
1.51-rerecording-v7 av desync

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/snes9x-rr#44]
Replay a movie like http://tasvideos.org/3019S.html and dump AVI for several thousands frames (some 10-15 minutes). Even if you select audio rate of 48KHz, the audio in the dump goes out of sync: damage and attacks are the most obvious example near the end if the video.

This doesn't happen in v6.

**Comment by gocha** [comment]
@vadosnaprimer I think the following build should have no problem.
https://ci.appveyor.com/project/gocha/snes9x-rr-tasvideos/builds/30215502/artifacts

**Comment by vadosnaprimer** [comment]
That fixes it! Thanks! I wonder if v7 can be considered deprecated.

**Comment by gocha** [comment]
Created a new release of [v7.1](https://github.com/TASVideos/snes9x-rr/releases/tag/snes9x-151-v7.1) for convenience.
